{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "cloud-provider-phoenixnap.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.annotations }}
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: 'true'
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: '{{ .Values.clusterRole.name }}'
rules:
  - apiGroups:
      - ''
    resources:
      - namespaces
    verbs:
      - get
  - apiGroups:
      - ''
    resources:
      - endpoints
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - '*'
  - apiGroups:
      - ''
    resources:
      - nodes/status
    verbs:
      - patch
  - apiGroups:
      - ''
    resources:
      - services
    verbs:
      - get
      - list
      - patch
      - update
      - watch
      - create
  - apiGroups:
      - ''
    resources:
      - services/status
    verbs:
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
{{- end }}
