{{ if .Values.configSecret.create }}
{{- $unused := required "You must set a PhoenixNAP client ID" .Values.config.clientID -}}
{{- $unused := required "You must set a PhoenixNAP client secret" .Values.config.clientSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cloud-provider-phoenixnap.configSecretName" . }}
  labels:
    {{- include "cloud-provider-phoenixnap.labels" . | nindent 4 }}
type: Opaque
data:
  cloud-sa.json: {{ .Values.config | toJson | b64enc | quote }}
{{ end }}
